### ISSUE TITLE
Why not make it into a pip module 

### ISSUE THREAD

**Issue by RjManhas** [Cloudzik1337/Interactive-Python-Menu#1]
Hello, @Cloudzik1337 why don't you just add this project to be a pip module so people don't have to download the GitHub repo?
I feel this would make it easier to use.

**Comment by Cloudzik1337** [comment]
Hi, it's my first project that I believe could be helpful for others, and I have never published any project to PyPI before. Is there any way to contact you (Discord, Telegram, etc.) to make that happen?

**Comment by Cloudzik1337** [comment]
No response for 2 days closing.

**Comment by tanngo2510** [comment]
> Hi, it's my first project that I believe could be helpful for others, and I have never published any project to PyPI before. Is there any way to contact you (Discord, Telegram, etc.) to make that happen?

Hello @Cloudzik1337, you can publish this project to PyPI by creating an account on PyPI, verifying the account and enabling 2FA. After that, you go to https://pypi.org/manage/account/publishing/ to publish your project.
